# Generated by Django 3.2.5 on 2021-07-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_auto_20210704_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='grade',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
